# Prefix
unbind C-b
set-option -g prefix M-a
bind-key M-a send-prefix

# Panes splitting
unbind \"
unbind %
bind | split-window -h
bind - split-window -v

# Panes switching
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Panes resizing
bind C-h resize-pane -L 4
bind C-j resize-pane -D 4
bind C-k resize-pane -U 4
bind C-l resize-pane -R 4

# set-window-option -g pane-border-status off

# Reload
bind r source-file ~/.config/tmux/tmux.conf
