import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[font]
normal = { family = "GeistMonoNerdFontMono", style = "Regular" }
italic = { family = "GeistMonoNerdFontMono", style = "Italic" }
size = 18
